add laravel 8 compatability by upgrading guzzle to ^7.0.1
berkayk/laravel-onesignal pull request #135
Opened 2020-09-08 18:12 UTC by ExpDev07

It does as the title suggests: updates guzzle to ^7.0.1 to support the new laravel 8 that is now released.

2020-09-08 23:13 UTC, atymic requested changes
See requested changes. Need to still allow 6.x & also allow laravel 8

2020-09-08 23:13 UTC, atymic commented on composer.json
> +    "guzzlehttp/guzzle": "^7.0.1",
```suggestion
    "guzzlehttp/guzzle": "^6.2 | ^7.0.1",
```

2020-09-08 23:13 UTC, atymic commented on composer.json
>      "illuminate/support": "4.*|5.*|6.*|7.*",
```suggestion
    "illuminate/support": "~5.5 || ~6.0 || ~7.0 || ~8.0",
```

2020-09-08 23:25 UTC, ExpDev07 commented
Thanks, made those changes now @atymic

2020-09-11 15:59 UTC, pedro-santiago commented
@berkayk would you mind merging this PR?

2020-09-12 06:00 UTC, merged